# Generated by Django 4.1.2 on 2023-04-12 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_obra_usuario_alter_obra_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='id',
        ),
        migrations.AddField(
            model_name='obra',
            name='mes',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
