# Generated by Django 4.1.2 on 2023-04-15 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_estado_id_obra_mes_alter_estado_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='ano',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2023)], verbose_name='Ano de referência'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='mes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês de referência'),
        ),
    ]
