# Generated by Django 4.1.2 on 2023-04-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_obra_ano_alter_obra_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='estado',
            new_name='estado_br',
        ),
    ]
