# Generated by Django 4.1.2 on 2023-04-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_rename_estado_obra_estado_br'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='estado_br',
            new_name='state_br',
        ),
    ]
