# Generated by Django 4.1.2 on 2023-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0008_alter_sicrocustomaodeobra_estado'),
        ('cadastros', '0006_rename_estado_br_obra_state_br'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAtualizado',
            fields=[
                ('sigla', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='obra',
            name='state_br',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
