# Generated by Django 4.1.2 on 2023-04-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_estadoatualizado_alter_obra_state_br_delete_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='state_br',
        ),
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.ForeignKey(default='SC', on_delete=django.db.models.deletion.PROTECT, to='cadastros.estadoatualizado'),
            preserve_default=False,
        ),
    ]
