# Generated by Django 4.1.2 on 2023-06-01 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0041_gruposicro_and_more'),
        ('cadastros', '0008_remove_obra_state_br_obra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CompsObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='composicoes.sicro')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.obra')),
            ],
        ),
    ]
