# Generated by Django 4.1.2 on 2023-04-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompGeral',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('produtividade', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unidade', models.CharField(max_length=10)),
                ('fic', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('quantidade', models.DecimalField(decimal_places=5, max_digits=20)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composicoes.compgeral')),
            ],
            options={
                'unique_together': {('comp', 'codigo')},
            },
        ),
    ]
