# Generated by Django 4.1.2 on 2023-04-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompGeral',
            new_name='Sicro',
        ),
        migrations.RenameModel(
            old_name='Labor',
            new_name='SicroMaodeObra',
        ),
    ]
