# Generated by Django 4.1.2 on 2023-04-12 11:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_estado_id_obra_mes_alter_estado_sigla'),
        ('composicoes', '0002_rename_compgeral_sicro_rename_labor_sicromaodeobra'),
    ]

    operations = [
        migrations.CreateModel(
            name='SicroCustoMaodeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2023)])),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unidade', models.CharField(max_length=10)),
                ('salario', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Salário')),
                ('engargos_totais', models.DecimalField(decimal_places=6, max_digits=7)),
                ('custo', models.DecimalField(decimal_places=4, max_digits=20)),
                ('periculosidade_insalubridade', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='Periculosidade/Insalubridade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.estado')),
            ],
        ),
    ]
