# Generated by Django 4.1.2 on 2023-04-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0004_alter_sicrocustomaodeobra_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoMaodeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
    ]
