# Generated by Django 4.1.2 on 2023-04-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0005_descricaomaodeobra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descricaomaodeobra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sicrocustomaodeobra',
            name='unidade',
        ),
        migrations.AddField(
            model_name='descricaomaodeobra',
            name='unidade',
            field=models.CharField(default='h', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descricaomaodeobra',
            name='codigo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
