# Generated by Django 4.1.2 on 2023-04-18 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0009_remove_sicrocustomaodeobra_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicrocustomaodeobra',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='composicoes.descricaomaodeobra', verbose_name='Código'),
        ),
    ]
