# Generated by Django 4.1.2 on 2023-04-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0011_sicrocustomaodeobra_desonerado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sicrocustomaodeobra',
            unique_together={('estado', 'mes', 'ano', 'desonerado', 'codigo')},
        ),
    ]
