# Generated by Django 4.1.2 on 2023-04-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0012_alter_sicrocustomaodeobra_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoEquipamento',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
    ]
