# Generated by Django 4.1.2 on 2023-04-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0014_custoequipamento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='custoequipamento',
            unique_together={('estado', 'mes', 'ano', 'desonerado', 'codigo')},
        ),
    ]
