# Generated by Django 4.1.2 on 2023-04-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0016_alter_custoequipamento_depreciacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoCompEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=5, max_digits=20)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='composicoes.descricaoequipamento', verbose_name='Código')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composicoes.sicro')),
            ],
            options={
                'unique_together': {('comp', 'codigo')},
            },
        ),
    ]
