# Generated by Django 4.1.2 on 2023-04-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0017_relacaocompequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacaocompequipamento',
            name='utilizacao_improdutiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacaocompequipamento',
            name='utilizacao_operativa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
