# Generated by Django 4.1.2 on 2023-04-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0018_relacaocompequipamento_utilizacao_improdutiva_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SicroCustoMaodeObra',
            new_name='MaodeObraCusto',
        ),
        migrations.RenameModel(
            old_name='DescricaoMaodeObra',
            new_name='MaodeObraDescricao',
        ),
        migrations.RenameModel(
            old_name='SicroMaodeObra',
            new_name='MaodeObraRelacaoComp',
        ),
        migrations.AlterField(
            model_name='relacaocompequipamento',
            name='utilizacao_improdutiva',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Utilização Improdutiva'),
        ),
        migrations.AlterField(
            model_name='relacaocompequipamento',
            name='utilizacao_operativa',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Utilização Operativa'),
        ),
    ]
