# Generated by Django 4.1.2 on 2023-04-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0019_rename_sicrocustomaodeobra_maodeobracusto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustoEquipamento',
            new_name='EquipamentoCusto',
        ),
        migrations.RenameModel(
            old_name='DescricaoEquipamento',
            new_name='EquipamentoDescricao',
        ),
        migrations.RenameModel(
            old_name='RelacaoCompEquipamento',
            new_name='EquipamentoRelacaoComp',
        ),
    ]
