# Generated by Django 4.1.2 on 2023-04-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0021_materialdescricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdescricao',
            name='codigo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
