# Generated by Django 4.1.2 on 2023-04-25 01:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0023_materialdescricao_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2023)])),
                ('desonerado', models.CharField(max_length=1)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Preço Unitário')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='composicoes.materialdescricao', verbose_name='Código')),
            ],
        ),
    ]
