# Generated by Django 4.1.2 on 2023-04-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0026_alter_materialrelacaocomp_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeauxiliarrelacaocomp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
