# Generated by Django 4.1.2 on 2023-04-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0027_alter_atividadeauxiliarrelacaocomp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcusto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
