# Generated by Django 4.1.2 on 2023-04-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0029_tempofixorelacaocomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempofixorelacaocomp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
