# Generated by Django 4.1.2 on 2023-04-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0030_alter_tempofixorelacaocomp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempofixorelacaocomp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
