# Generated by Django 4.1.2 on 2023-04-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0033_materialrelacaocomp_quantidade_tempo_fixo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrelacaocomp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
