# Generated by Django 4.1.2 on 2023-04-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0035_atividadeauxiliarrelacaocomp_quantidade_tempo_fixo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempoFixoRelacaoComp',
        ),
    ]
