# Generated by Django 4.1.2 on 2023-04-29 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0036_delete_tempofixorelacaocomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicro',
            name='fic',
        ),
        migrations.CreateModel(
            name='CompFIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2023)])),
                ('fic', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composicoes.sicro')),
            ],
        ),
    ]
