# Generated by Django 4.1.2 on 2023-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0037_remove_sicro_fic_compfic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compfic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
