# Generated by Django 4.1.2 on 2023-04-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0038_alter_compfic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compfic',
            old_name='comp',
            new_name='codigo',
        ),
    ]
