# Generated by Django 4.1.2 on 2023-05-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0039_rename_comp_compfic_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compfic',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composicoes.sicro', verbose_name='Código'),
        ),
        migrations.AddIndex(
            model_name='sicro',
            index=models.Index(fields=['codigo'], name='composicoes_codigo_93086b_idx'),
        ),
    ]
