# Generated by Django 4.1.2 on 2023-05-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composicoes', '0040_alter_compfic_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSicro',
            fields=[
                ('grupo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.AddIndex(
            model_name='maodeobrarelacaocomp',
            index=models.Index(fields=['comp', 'codigo'], name='composicoes_comp_id_0031e5_idx'),
        ),
    ]
